CREATE TABLE `ecommerce_vendor_order_item` (

  `ecommerce_vendor_order_item_id`      BIGINT(19) NOT NULL,
  `ecommerce_vendor_order_id`           BIGINT(19) NOT NULL,
  `ecommerce_category_id`               BIGINT(19) NOT NULL,
  `quantity`                            INT(11),
  `total_price`                         DECIMAL(15, 4),
  `ecommerce_product_id`                BIGINT(19) NOT NULL,
  `ecommerce_product_variant_id`        BIGINT(19),
  `product_url`                         VARCHAR(255),
  `product_name`                        VARCHAR(255),
  `product_price`                       DECIMAL(15, 4),
  `product_reference`                   VARCHAR(255),
  `product_discount_price`              DECIMAL(15, 4),
  `product_description`                 VARCHAR(255),
  `product_main_image`                  VARCHAR(255),
  `product_main_image_platform_file_id` BIGINT(19),
  `variant_reference`                   VARCHAR(255),
  `ecommerce_color_id`                  BIGINT(19),
  `color_value`                         VARCHAR(255),
  `color_code`                          VARCHAR(255),
  `color_img`                           VARCHAR(255),
  `color_reference`                     VARCHAR(255),
  `color_img_platform_file_id`          BIGINT(19),
  `ecommerce_size_id`                   BIGINT(19),
  `size_value`                          VARCHAR(255),
  `size_reference`                      VARCHAR(255),

  KEY (`ecommerce_vendor_order_id`),
  KEY (`ecommerce_category_id`),
  KEY (`quantity`),
  KEY (`total_price`),
  KEY (`ecommerce_product_id`),
  KEY (`ecommerce_product_variant_id`),
  KEY (`product_url`),
  KEY (`product_name`),
  KEY (`product_price`),
  KEY (`product_discount_price`),
  KEY (`product_description`),
  KEY (`product_main_image`),
  KEY (`product_main_image_platform_file_id`),
  KEY (`variant_reference`),
  KEY (`ecommerce_color_id`),
  KEY (`color_value`),
  KEY (`color_code`),
  KEY (`color_img`),
  KEY (`color_reference`),
  KEY (`color_img_platform_file_id`),
  KEY (`ecommerce_size_id`),
  KEY (`size_value`),
  KEY (`size_reference`),
  PRIMARY KEY (`ecommerce_vendor_order_item_id`)
);