INSERT INTO platform_rest (platform_rest_id, name, description, java_class, version)
VALUES
  (18, 'Orders Single Service Get', 'Orders Single Service Get', 'com.angkorteam.ecommerce.controller.OrdersSingleServiceGet', 1),
  (17, 'Orders Service Get', 'Orders Service Get', 'com.angkorteam.ecommerce.controller.OrdersServiceGet', 1),
  (16, 'Orders Service Post', 'Orders Service Post', 'com.angkorteam.ecommerce.controller.OrdersServicePost', 1),
  (15, 'Cart Discounts Service Post', 'Cart Discounts Service Post', 'com.angkorteam.ecommerce.controller.CartDiscountsServicePost', 1),
  (14, 'Cart Discounts Single Service Delete', 'Cart Discounts Single Service Delete', 'com.angkorteam.ecommerce.controller.CartDiscountsSingleServiceDelete', 1),
  (13, 'Cart Item Service Delete', 'Cart Item Service Delete', 'com.angkorteam.ecommerce.controller.CartItemServiceDelete', 1),
  (12, 'Cart Item Service Put', 'Cart Item Service Put', 'com.angkorteam.ecommerce.controller.CartItemServicePut', 1),
  (11, 'Cart Service Post', 'Cart Service Post', 'com.angkorteam.ecommerce.controller.CartServicePost', 1),
  (10, 'Cart Info Service Get', 'Cart Info Service Get', 'com.angkorteam.ecommerce.controller.CartInfoServiceGet', 1),
  (9, 'Cart Service Get', 'Cart Service Get', 'com.angkorteam.ecommerce.controller.CartServiceGet', 1),
  (8, 'Wishlist Single Service Delete', 'Wishlist Single Service Delete', 'com.angkorteam.ecommerce.controller.WishlistSingleServiceDelete', 1),
  (7, 'Wishlist Service Post', 'Wishlist Service Post', 'com.angkorteam.ecommerce.controller.WishlistServicePost', 1),
  (6, 'Wishlist Is In Wishlist Service Get', 'Wishlist Is In Wishlist Service Get', 'com.angkorteam.ecommerce.controller.WishlistIsInWishlistServiceGet', 1),
  (5, 'User Change Password Service Put', 'User Change Password Service Put', 'com.angkorteam.ecommerce.controller.UserChangePasswordServicePut', 1),
  (4, 'User Single Service Put', 'User Single Service Put', 'com.angkorteam.ecommerce.controller.UserSingleServicePut', 1),
  (1, 'System Controller', 'System Controller', 'com.angkorteam.ecommerce.controller.SystemController', 1),
  (2, 'Wishlist Service Get', 'Wishlist Service Get', 'com.angkorteam.ecommerce.controller.WishlistServiceGet', 1),
  (3, 'User Single Service Get', 'User Single Service Get', 'com.angkorteam.ecommerce.controller.UserSingleServiceGet', 1);