INSERT INTO `platform_page` (`platform_page_id`, `platform_layout_id`, `path`, `html_title`, `page_title`, `page_description`, `java_class`, `version`)
VALUES
  (169, 1, '/ecommerce/vendor/register', 'eCommerce Vendor Register', 'eCommerce Vendor Register', 'eCommerce Vendor Register', 'com.angkorteam.ecommerce.page.VendorRegisterPage', 1),
  (168, 1, '/ecommerce/vendor/order/review', 'eCommerce Vendor Order Review', 'eCommerce Vendor Order Review', 'eCommerce Vendor Order Review', 'com.angkorteam.ecommerce.page.order.VendorOrderReviewPage', 1),
  (167, 1, '/ecommerce/vendor/order/browse', 'eCommerce Vendor Order Browse', 'eCommerce Vendor Order Browse', 'eCommerce Vendor Order Browse', 'com.angkorteam.ecommerce.page.order.VendorOrderBrowsePage', 1),
  (166, 1, '/ecommerce/customer/order/review', 'eCommerce Customer Order Review', 'eCommerce Customer Order Review', 'eCommerce Customer Order Review', 'com.angkorteam.ecommerce.page.order.CustomerOrderReviewPage', 1),
  (165, 1, '/ecommerce/customer/order/browse', 'eCommerce Customer Order Browse', 'eCommerce Customer Order Browse', 'eCommerce Customer Order Browse', 'com.angkorteam.ecommerce.page.order.CustomerOrderBrowsePage', 1),
  (164, 1, '/ecommerce/order/review', 'eCommerce Order Review', 'eCommerce Order Review', 'eCommerce Order Review', 'com.angkorteam.ecommerce.page.order.OrderReviewPage', 1),
  (163, 1, '/ecommerce/order/detail', 'eCommerce Order Detail', 'eCommerce Order Detail', 'eCommerce Order Detail', 'com.angkorteam.ecommerce.page.order.OrderDetailPage', 1),
  (162, 1, '/ecommerce/order/browse', 'eCommerce Order Browse', 'eCommerce Order Browse', 'eCommerce Order Browse', 'com.angkorteam.ecommerce.page.order.OrderBrowsePage', 1),
  (159, 1, '/ecommerce/shop/modify', 'eCommerce Shop Modify', 'eCommerce Shop Modify', 'eCommerce Shop Modify', 'com.angkorteam.ecommerce.page.shop.ShopModifyPage', 1),
  (160, 1, '/ecommerce/shop/create', 'eCommerce Shop Create', 'eCommerce Shop Create', 'eCommerce Shop Create', 'com.angkorteam.ecommerce.page.shop.ShopCreatePage', 1),
  (161, 1, '/ecommerce/shop/browse', 'eCommerce Shop Browse', 'eCommerce Shop Browse', 'eCommerce Shop Browse', 'com.angkorteam.ecommerce.page.shop.ShopBrowsePage', 1),
  (156, 1, '/ecommerce/shipping/modify', 'eCommerce Shipping Modify', 'eCommerce Shipping Modify', 'eCommerce Shipping Modify', 'com.angkorteam.ecommerce.page.shipping.ShippingModifyPage', 1),
  (157, 1, '/ecommerce/shipping/create', 'eCommerce Shipping Create', 'eCommerce Shipping Create', 'eCommerce Shipping Create', 'com.angkorteam.ecommerce.page.shipping.ShippingCreatePage', 1),
  (158, 1, '/ecommerce/shipping/browse', 'eCommerce Shipping Browse', 'eCommerce Shipping Browse', 'eCommerce Shipping Browse', 'com.angkorteam.ecommerce.page.shipping.ShippingBrowsePage', 1),
  (154, 1, '/ecommerce/product/variant/gallery/create', 'eCommerce Product Variant Gallery Create', 'eCommerce Product Variant Gallery Create', 'eCommerce Product Variant Gallery Create', 'com.angkorteam.ecommerce.page.product.ProductVariantGalleryCreatePage', 1),
  (155, 1, '/ecommerce/product/variant/gallery/browse', 'eCommerce Product Variant Gallery Browse', 'eCommerce Product Variant Gallery Browse', 'eCommerce Product Variant Gallery Browse', 'com.angkorteam.ecommerce.page.product.ProductVariantGalleryBrowsePage', 1),
  (151, 1, '/ecommerce/product/variant/modify', 'eCommerce Product Variant Modify', 'eCommerce Product Variant Modify', 'eCommerce Product Variant Modify', 'com.angkorteam.ecommerce.page.product.ProductVariantModifyPage', 1),
  (152, 1, '/ecommerce/product/variant/create', 'eCommerce Product Variant Create', 'eCommerce Product Variant Create', 'eCommerce Product Variant Create', 'com.angkorteam.ecommerce.page.product.ProductVariantCreatePage', 1),
  (153, 1, '/ecommerce/product/variant/browse', 'eCommerce Product Variant Browse', 'eCommerce Product Variant Browse', 'eCommerce Product Variant Browse', 'com.angkorteam.ecommerce.page.product.ProductVariantBrowsePage', 1),
  (149, 1, '/ecommerce/product/gallery/create', 'eCommerce Product Gallery Create', 'eCommerce Product Gallery Create', 'eCommerce Product Gallery Create', 'com.angkorteam.ecommerce.page.product.ProductGalleryCreatePage', 1),
  (150, 1, '/ecommerce/product/gallery/browse', 'eCommerce Product Gallery Browse', 'eCommerce Product Gallery Browse', 'eCommerce Product Gallery Browse', 'com.angkorteam.ecommerce.page.product.ProductGalleryBrowsePage', 1),
  (148, 1, '/ecommerce/product/review', 'eCommerce Product Review', 'eCommerce Product Review', 'eCommerce Product Review', 'com.angkorteam.ecommerce.page.product.ProductReviewPage', 1),
  (147, 1, '/ecommerce/product/modify', 'eCommerce Product Modify', 'eCommerce Product Modify', 'eCommerce Product Modify', 'com.angkorteam.ecommerce.page.product.ProductModifyPage', 1),
  (146, 1, '/ecommerce/product/create', 'eCommerce Product Create', 'eCommerce Product Create', 'eCommerce Product Create', 'com.angkorteam.ecommerce.page.product.ProductCreatePage', 1),
  (145, 1, '/ecommerce/product/browse', 'eCommerce Product Browse', 'eCommerce Product Browse', 'eCommerce Product Browse', 'com.angkorteam.ecommerce.page.product.ProductBrowsePage', 1),
  (142, 1, '/ecommerce/discount/modify', 'eCommerce Discount Modify', 'eCommerce Discount Modify', 'eCommerce Discount Modify', 'com.angkorteam.ecommerce.page.discount.DiscountModifyPage', 1),
  (143, 1, '/ecommerce/discount/create', 'eCommerce Discount Create', 'eCommerce Discount Create', 'eCommerce Discount Create', 'com.angkorteam.ecommerce.page.discount.DiscountCreatePage', 1),
  (144, 1, '/ecommerce/discount/browse', 'eCommerce Discount Browse', 'eCommerce Discount Browse', 'eCommerce Discount Browse', 'com.angkorteam.ecommerce.page.discount.DiscountBrowsePage', 1),
  (139, 1, '/ecommerce/category/modify', 'eCommerce Category Modify', 'eCommerce Category Modify', 'eCommerce Category Modify', 'com.angkorteam.ecommerce.page.category.CategoryModifyPage', 1),
  (140, 1, '/ecommerce/category/create', 'eCommerce Category Create', 'eCommerce Category Create', 'eCommerce Category Create', 'com.angkorteam.ecommerce.page.category.CategoryCreatePage', 1),
  (141, 1, '/ecommerce/category/browse', 'eCommerce Category Browse', 'eCommerce Category Browse', 'eCommerce Category Browse', 'com.angkorteam.ecommerce.page.category.CategoryBrowsePage', 1),
  (136, 1, '/ecommerce/brand/modify', 'eCommerce Brand Modify', 'eCommerce Brand Modify', 'eCommerce Brand Modify', 'com.angkorteam.ecommerce.page.brand.BrandModifyPage', 1),
  (137, 1, '/ecommerce/brand/create', 'eCommerce Brand Create', 'eCommerce Brand Create', 'eCommerce Brand Create', 'com.angkorteam.ecommerce.page.brand.BrandCreatePage', 1),
  (138, 1, '/ecommerce/brand/browse', 'eCommerce Brand Browse', 'eCommerce Brand Browse', 'eCommerce Brand Browse', 'com.angkorteam.ecommerce.page.brand.BrandBrowsePage', 1),
  (133, 1, '/ecommerce/payment/modify', 'eCommerce Payment Modify', 'eCommerce Payment Modify', 'eCommerce Payment Modify', 'com.angkorteam.ecommerce.page.payment.PaymentModifyPage', 1),
  (134, 1, '/ecommerce/payment/create', 'eCommerce Payment Create', 'eCommerce Payment Create', 'eCommerce Payment Create', 'com.angkorteam.ecommerce.page.payment.PaymentCreatePage', 1),
  (135, 1, '/ecommerce/payment/browse', 'eCommerce Payment Browse', 'eCommerce Payment Browse', 'eCommerce Payment Browse', 'com.angkorteam.ecommerce.page.payment.PaymentBrowsePage', 1),
  (131, 1, '/ecommerce/size/create', 'eCommerce Size Create', 'eCommerce Size Create', 'eCommerce Size Create', 'com.angkorteam.ecommerce.page.size.SizeCreatePage', 1),
  (132, 1, '/ecommerce/size/browse', 'eCommerce Size Browse', 'eCommerce Size Browse', 'eCommerce Size Browse', 'com.angkorteam.ecommerce.page.size.SizeBrowsePage', 1),
  (128, 1, '/ecommerce/branch/transport/modify', 'eCommerce Branch Transport Modify', 'eCommerce Branch Transport Modify', 'eCommerce Branch Transport Modify', 'com.angkorteam.ecommerce.page.branch.BranchTransportModifyPage', 1),
  (129, 1, '/ecommerce/branch/transport/create', 'eCommerce Branch Transport Create', 'eCommerce Branch Transport Create', 'eCommerce Branch Transport Create', 'com.angkorteam.ecommerce.page.branch.BranchTransportCreatePage', 1),
  (130, 1, '/ecommerce/branch/transport/browse', 'eCommerce Branch Transport Browse', 'eCommerce Branch Transport Browse', 'eCommerce Branch Transport Browse', 'com.angkorteam.ecommerce.page.branch.BranchTransportBrowsePage', 1),
  (125, 1, '/ecommerce/branch/opening/modify', 'eCommerce Branch Opening Modify', 'eCommerce Branch Opening Modify', 'eCommerce Branch Opening Modify', 'com.angkorteam.ecommerce.page.branch.BranchOpeningModifyPage', 1),
  (126, 1, '/ecommerce/branch/opening/create', 'eCommerce Branch Opening Create', 'eCommerce Branch Opening Create', 'eCommerce Branch Opening Create', 'com.angkorteam.ecommerce.page.branch.BranchOpeningCreatePage', 1),
  (127, 1, '/ecommerce/branch/opening/browse', 'eCommerce Branch Opening Browse', 'eCommerce Branch Opening Browse', 'eCommerce Branch Opening Browse', 'com.angkorteam.ecommerce.page.branch.BranchOpeningBrowsePage', 1),
  (122, 1, '/ecommerce/branch/modify', 'eCommerce Branch Modify', 'eCommerce Branch Modify', 'eCommerce Branch Modify', 'com.angkorteam.ecommerce.page.branch.BranchModifyPage', 1),
  (123, 1, '/ecommerce/branch/create', 'eCommerce Branch Create', 'eCommerce Branch Create', 'eCommerce Branch Create', 'com.angkorteam.ecommerce.page.branch.BranchCreatePage', 1),
  (124, 1, '/ecommerce/branch/browse', 'eCommerce Branch Browse', 'eCommerce Branch Browse', 'eCommerce Branch Browse', 'com.angkorteam.ecommerce.page.branch.BranchBrowsePage', 1),
  (119, 1, '/ecommerce/article/modify', 'eCommerce Article Modify', 'eCommerce Article Modify', 'eCommerce Article Modify', 'com.angkorteam.ecommerce.page.article.ArticleModifyPage', 1),
  (120, 1, '/ecommerce/article/create', 'eCommerce Article Create', 'eCommerce Article Create', 'eCommerce Article Create', 'com.angkorteam.ecommerce.page.article.ArticleCreatePage', 1),
  (121, 1, '/ecommerce/article/browse', 'eCommerce Article Browse', 'eCommerce Article Browse', 'eCommerce Article Browse', 'com.angkorteam.ecommerce.page.article.ArticleBrowsePage', 1),
  (116, 1, '/ecommerce/banner/browse', 'eCommerce Banner Browse', 'eCommerce Banner Browse', 'eCommerce Banner Browse', 'com.angkorteam.ecommerce.page.banner.BannerBrowsePage', 1),
  (117, 1, '/ecommerce/banner/create', 'eCommerce Banner Create', 'eCommerce Banner Create', 'eCommerce Banner Create', 'com.angkorteam.ecommerce.page.banner.BannerCreatePage', 1),
  (118, 1, '/ecommerce/banner/modify', 'eCommerce Banner Modify', 'eCommerce Banner Modify', 'eCommerce Banner Modify', 'com.angkorteam.ecommerce.page.banner.BannerModifyPage', 1),
  (1, 1, '/platform/dashboard', 'Platform Dashboard', 'Platform Dashboard', 'Platform Dashboard', 'com.angkorteam.platform.page.DashboardPage', 1),
  (2, 1, '/platform/menu/browse', 'Platform Menu Browse', 'Platform Menu Browse', 'Platform Menu Browse', 'com.angkorteam.platform.page.menu.MenuBrowsePage', 1),
  (5, 1, '/platform/menu/item/browse', 'Platform Menu Item Browse', 'Platform Menu Item Browse', 'Platform Menu Item Browse', 'com.angkorteam.platform.page.menuitem.MenuItemBrowsePage', 1),
  (8, 1, '/platform/section/browse', 'Platform Section Browse', 'Platform Section Browse', 'Platform Section Browse', 'com.angkorteam.platform.page.section.SectionBrowsePage', 1),
  (11, 1, '/platform/layout/browse', 'Platform Layout Browse', 'Platform Layout Browse', 'Platform Layout Browse', 'com.angkorteam.platform.page.layout.LayoutBrowsePage', 1),
  (16, 1, '/platform/page/browse', 'Platform Page Browse', 'Platform Page Browse', 'Platform Page Browse', 'com.angkorteam.platform.page.page.PageBrowsePage', 1),
  (19, 1, '/platform/role/browse', 'Platform Role Browse', 'Platform Role Browse', 'Platform Role Browse', 'com.angkorteam.platform.page.role.RoleBrowsePage', 1),
  (22, 1, '/platform/file/browse', 'Platform File Browse', 'Platform File Browse', 'Platform File Browse', 'com.angkorteam.platform.page.file.FileBrowsePage', 1),
  (27, 1, '/platform/login', 'Platform Login', 'Platform Login', 'Platform Login', 'com.angkorteam.platform.page.LoginPage', 1),
  (28, 1, '/platform/logout', 'Platform Logout', 'Platform Logout', 'Platform Logout', 'com.angkorteam.platform.page.LogoutPage', 1),
  (29, 1, '/platform/rest/browse', 'Platform Rest Browse', 'Platform Rest Browse', 'Platform Rest Browse', 'com.angkorteam.platform.page.rest.RestBrowsePage', 1),
  (32, 1, '/platform/setting', 'Platform Setting', 'Platform Setting', 'Platform Setting', 'com.angkorteam.platform.page.SettingPage', 1),
  (23, 1, '/platform/user/browse', 'Platform User Browse', 'Platform User Browse', 'Platform User Browse', 'com.angkorteam.platform.page.user.UserBrowsePage', 1),
  (100, 1, '/platform/file/create', 'Platform File Create', 'Platform File Create', 'Platform File Create', 'com.angkorteam.platform.page.file.FileCreatePage', 1),
  (101, 1, '/platform/file/modify', 'Platform File Modify', 'Platform File Modify', 'Platform File Modify', 'com.angkorteam.platform.page.file.FileModifyPage', 1),
  (103, 1, '/platform/section/modify', 'Platform Section Modify', 'Platform Section Modify', 'Platform Section Modify', 'com.angkorteam.platform.page.section.SectionModifyPage', 1),
  (104, 1, '/platform/menu/item/modify', 'Platform Menu Item Modify', 'Platform Menu Item Modify', 'Platform Menu Item Modify', 'com.angkorteam.platform.page.menuitem.MenuItemModifyPage', 1),
  (105, 1, '/platform/menu/modify', 'Platform Menu Modify', 'Platform Menu Modify', 'Platform Menu Modify', 'com.angkorteam.platform.page.menu.MenuModifyPage', 1),
  (106, 1, '/platform/layout/modify', 'Platform Layout Modify', 'Platform Layout Modify', 'Platform Layout Modify', 'com.angkorteam.platform.page.layout.LayoutModifyPage', 1),
  (107, 1, '/platform/page/modify', 'Platform Page Modify', 'Platform Page Modify', 'Platform Page Modify', 'com.angkorteam.platform.page.page.PageModifyPage', 1),
  (108, 1, '/platform/role/create', 'Platform Role Create', 'Platform Role Create', 'Platform Role Create', 'com.angkorteam.platform.page.role.RoleCreatePage', 1),
  (109, 1, '/platform/role/modify', 'Platform Role Modify', 'Platform Role Modify', 'Platform Role Modify', 'com.angkorteam.platform.page.role.RoleModifyPage', 1),
  (110, 1, '/platform/user/modify', 'Platform User Modify', 'Platform User Modify', 'Platform User Modify', 'com.angkorteam.platform.page.user.UserModifyPage', 1),
  (111, 1, '/platform/user/create', 'Platform User Create', 'Platform User Create', 'Platform User Create', 'com.angkorteam.platform.page.user.UserCreatePage', 1),
  (112, 1, '/platform/user/password', 'Platform User Password', 'Platform User Password', 'Platform User Password', 'com.angkorteam.platform.page.user.UserPasswordPage', 1),
  (113, 1, '/platform/rest/modify', 'Platform Rest Modify', 'Platform Rest Modify', 'Platform Rest Modify', 'com.angkorteam.platform.page.rest.RestModifyPage', 1),
  (114, 1, '/ecommerce/color/browse', 'eCommerce Color Browse', 'eCommerce Color Browse', 'eCommerce Color Browse', 'com.angkorteam.ecommerce.page.color.ColorBrowsePage', 1),
  (115, 1, '/ecommerce/color/create', 'eCommerce Color Create', 'eCommerce Color Create', 'eCommerce Color Create', 'com.angkorteam.ecommerce.page.color.ColorCreatePage', 1);