CREATE TABLE `ecommerce_order` (

  `ecommerce_order_id`           BIGINT(19) NOT NULL,
  `ecommerce_shipping_id`        BIGINT(19) NOT NULL,
  `ecommerce_payment_id`         BIGINT(19) NOT NULL,
  `platform_user_id`             BIGINT(19) NOT NULL,
  `ecommerce_discount_coupon_id` BIGINT(19),
  `ecommerce_discount_id`        BIGINT(19),
  `coupon_type`                  VARCHAR(20),
  `coupon_value`                 DECIMAL(15, 4),
  `discount_amount`              DECIMAL(15, 4),
  `sub_total_amount`             DECIMAL(15, 4),
  `total_amount`                 DECIMAL(15, 4),
  `grand_total_amount`           DECIMAL(15, 4),
  `name`                         VARCHAR(255),
  `street`                       VARCHAR(255),
  `house_number`                 VARCHAR(255),
  `city`                         VARCHAR(255),
  `zip`                          VARCHAR(255),
  `email`                        VARCHAR(255),
  `phone`                        VARCHAR(255),
  `note`                         VARCHAR(255),
  `date_created`                 DATETIME,
  `buyer_status`                 VARCHAR(255),
  `order_status`                 VARCHAR(255),
  `ecommerce_region_id`          BIGINT(19),
  `shipping_name`                VARCHAR(255),
  `shipping_price`               DECIMAL(15, 4),
  `shipping_price_addon`         DECIMAL(15, 4),
  `payment_name`                 VARCHAR(255),
  `payment_price`                DECIMAL(15, 4),

  KEY (`ecommerce_discount_coupon_id`),
  KEY (`ecommerce_discount_id`),
  KEY (`coupon_type`),
  KEY (`coupon_value`),
  KEY (`ecommerce_shipping_id`),
  KEY (`ecommerce_payment_id`),
  KEY (`ecommerce_region_id`),
  KEY (`platform_user_id`),
  KEY (`name`),
  KEY (`street`),
  KEY (`house_number`),
  KEY (`city`),
  KEY (`zip`),
  KEY (`email`),
  KEY (`date_created`),
  KEY (`phone`),
  KEY (`grand_total_amount`),
  KEY (`total_amount`),
  KEY (`sub_total_amount`),
  KEY (`discount_amount`),
  KEY (`shipping_price_addon`),
  KEY (`note`),
  KEY (`shipping_name`),
  KEY (`shipping_price`),
  KEY (`buyer_status`),
  KEY (`order_status`),
  PRIMARY KEY (`ecommerce_order_id`)
);