CREATE TABLE `platform_user` (

  `platform_user_id` BIGINT(19)   NOT NULL,
  `login`            VARCHAR(255) NOT NULL,
  `password`         VARCHAR(255) NOT NULL,
  `full_name`        VARCHAR(255) NOT NULL,
  `platform_role_id` BIGINT(19)   NOT NULL,
  `system`           BIT(1)       NOT NULL DEFAULT 0,
  `status`           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  `version`          INT(11)      NOT NULL DEFAULT 1,
  `access_token`     VARCHAR(255) NOT NULL,
  `street`           VARCHAR(255),
  `city`             VARCHAR(255),
  `house_number`     VARCHAR(255),
  `zip`              VARCHAR(255),
  `phone`            VARCHAR(255),
  `gender`           VARCHAR(10),
  `country`          VARCHAR(100),

  KEY (`street`),
  KEY (`city`),
  KEY (`house_number`),
  KEY (`zip`),
  KEY (`phone`),
  KEY (`gender`),
  KEY (`country`),
  KEY (`full_name`),
  KEY (`password`),
  KEY (`platform_role_id`),
  KEY (`system`),
  KEY (`status`),
  KEY (`version`),
  UNIQUE KEY (`access_token`),
  UNIQUE KEY (`login`),
  PRIMARY KEY (`platform_user_id`)
);